linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  unused:
    check-exported: true
  unparam:
    check-exported: true

# Also see stricter setup: https://github.com/golangci/golangci-lint/blob/master/.golangci.yml
linters:
  disable-all: true
  enable:
    # Enabled by default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

    # Disabled by default
    - bodyclose
    - depguard
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - golint
    - gosec
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - unconvert
    - unparam

run:
  deadline: 2m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
